#!/usr/bin/bash

gen_roi --mri_data_dir /data1/A182/mri_subjects --search_space /data1/A182/mri_subjects/A182_ROI_Scripts/A182_BC_ROI_from_clust/ang/ang+tlrc.HEAD --func_pattern stats.*REML+*.HEAD* --anat_tlrc *ns+tlrc.HEAD --contrast_subbrick 38 --copy_anat_pattern Sag*ns+orig* --roi_size 50 --clip 0.2 --warped_ss_prefix ang_ss+orig --output_dir rois/ANG --output_roi_prefix ANG_50 --make_ss_snapshots --create_masked_func --save_peak_prefix peak_vox $@
gen_roi --mri_data_dir /data1/A182/mri_subjects --search_space /data1/A182/mri_subjects/A182_ROI_Scripts/A182_BC_ROI_from_clust/awfa/awfa+tlrc.HEAD --func_pattern stats.*REML+*.HEAD* --anat_tlrc *ns+tlrc.HEAD --contrast_subbrick 29 --copy_anat_pattern Sag*ns+orig* --roi_size 50 --clip 0.2 --warped_ss_prefix awfa_ss+orig --output_dir rois/AWFA --output_roi_prefix AWFA_50 --make_ss_snapshots --create_masked_func --save_peak_prefix peak_vox $@
gen_roi --mri_data_dir /data1/A182/mri_subjects --search_space /data1/A182/mri_subjects/A182_ROI_Scripts/A182_BC_ROI_from_clust/ifg/ifg+tlrc.HEAD --func_pattern stats.*REML+*.HEAD* --anat_tlrc *ns+tlrc.HEAD --contrast_subbrick 38 --copy_anat_pattern Sag*ns+orig* --roi_size 50 --clip 0.2 --warped_ss_prefix ifg_ss+orig --output_dir rois/IFG --output_roi_prefix IFG_50 --make_ss_snapshots --create_masked_func --save_peak_prefix peak_vox $@
gen_roi --mri_data_dir /data1/A182/mri_subjects --search_space /data1/A182/mri_subjects/A182_ROI_Scripts/A182_BC_ROI_from_clust/smg/smg+tlrc.HEAD --func_pattern stats.*REML+*.HEAD* --anat_tlrc *ns+tlrc.HEAD --contrast_subbrick 38 --copy_anat_pattern Sag*ns+orig* --roi_size 50 --clip 0.2 --warped_ss_prefix smg_ss+orig --output_dir rois/SMG --output_roi_prefix SMG_50 --make_ss_snapshots --create_masked_func --save_peak_prefix peak_vox $@
gen_roi --mri_data_dir /data1/A182/mri_subjects --search_space /data1/A182/mri_subjects/A182_ROI_Scripts/A182_BC_ROI_from_clust/stgp/stgp+tlrc.HEAD --func_pattern stats.*REML+*.HEAD* --anat_tlrc *ns+tlrc.HEAD --contrast_subbrick 38 --copy_anat_pattern Sag*ns+orig* --roi_size 50 --clip 0.2 --warped_ss_prefix stgp_ss+orig --output_dir rois/STGP --output_roi_prefix STGP_50 --make_ss_snapshots --create_masked_func --save_peak_prefix peak_vox $@
gen_roi --mri_data_dir /data1/A182/mri_subjects --search_space /data1/A182/mri_subjects/A182_ROI_Scripts/A182_BC_ROI_from_clust/vwfa/VWFA_restricted+tlrc.HEAD --func_pattern stats.*REML+*.HEAD* --anat_tlrc *ns+tlrc.HEAD --contrast_subbrick 26 --copy_anat_pattern Sag*ns+orig* --roi_size 50  --clip 0.2 --warped_ss_prefix vwfa_ss+orig --output_dir rois/VWFA --output_roi_prefix VWFA_50 --make_ss_snapshots --create_masked_func --save_peak_prefix peak_vox $@
gen_roi --mri_data_dir /data1/A182/mri_subjects --search_space /data1/A182/mri_subjects/A182_ROI_Scripts/A182_BC_ROI_from_clust/vwfa/VWFA_restricted+tlrc.HEAD --func_pattern stats.*REML+*.HEAD* --anat_tlrc *ns+tlrc.HEAD --contrast_subbrick 14 --copy_anat_pattern Sag*ns+orig* --roi_size 50  --clip 0.2 --warped_ss_prefix vwfa_ss+orig --output_dir rois/VWFA2 --output_roi_prefix VWFA2_50 --make_ss_snapshots --create_masked_func --save_peak_prefix peak_vox $@
